ARG VARIANT=22.1-apline

FROM node:22.16-apline AS builder

# Required to build application
# RUN npm install --no-audit --no-fund --loglevel=warn

WORKDIR /usr/src/app
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ../package*.json ./
ARG NODE_ENV=development
# RUN npm ci --no-audit --no-fund --loglevel=warn
COPY . .
# RUN npm start

FROM node:\$\{VARIANT\}

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates

RUN curl -fsSLk https://pgp.mongodb.com/server-7.0.asc | \
   gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg \
   --dearmor

RUN wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | apt-key add -
RUN touch /etc/apt/sources.list.d/mongodb-org-7.0.list
RUN echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-7.0.list

RUN npm update -g npm
RUN apt-get update
RUN apt-get install -y iputils-ping
RUN apt-get install -y sudo
RUN apt-get install -y vim
RUN apt-get install -y net-tools
RUN apt-get install -y kafkacat
RUN apt-get install -y git
RUN apt-get install -y librdkafka-dev

WORKDIR /usr/src/app
COPY --from=builder --chown=node:node /usr/src/app .
RUN chmod +x ./docker/node/docker-entrypoint.sh
RUN chmod +x ./docker/kafka/InstallExtras.sh
USER node
ENTRYPOINT ["./docker/node/docker-entrypoint.sh"]
